import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * KELOMPOK 5 / SI 1A
 * author : RIFAT ZULFAN MANAF
 */

public class KHS_Mahasiswa extends javax.swing.JFrame {

    public static String nama, nim, matkul, sks, uts, uas, ukk, predikat, na, skala, ipk;
    public static double UTS, UAS, UKK, IPK, NA, Skala, SKS,
            total, JTOTAL = 0, JSKS = 0, JJUMLAH = 0;

    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

    int baris = 0;
    static Object kolom[] = {"Mata Kuliah", "SKS", "Nilai Angka", "Nilai Huruf"};
    DefaultTableModel tabel = new DefaultTableModel(kolom, baris);

    /**
     * Creates new form KHS_MAHASISWA
     */
    public KHS_Mahasiswa() {
        initComponents();
        model.addElement("Pilih");
        model.addElement("Pendidikan Agama");
        model.addElement("Matematika Komputasi");
        model.addElement("Algoritma dan Pemrograman");
        model.addElement("Dasar Teknologi Informasi");
        model.addElement("Jaringan Komputer");
        model.addElement("Pemrograman Mobile");

        CBMATKUL.setModel(model);
        TABELKHS.setModel(tabel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CBMATKUL = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TSKS = new javax.swing.JTextField();
        TUTS = new javax.swing.JTextField();
        TUAS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TUKK = new javax.swing.JTextField();
        BTAMBAH = new javax.swing.JButton();
        BRESET = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABELKHS = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false; //Disallow the editing of any cell
            }
        };
        jLabel11 = new javax.swing.JLabel();
        TIPK = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("KHS MAHASISWA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 0, 28)); // NOI18N
        jLabel1.setText("KHS MAHASISWA");

        jLabel2.setText("Nama              ");

        jLabel3.setText("Nama              ");

        jLabel4.setText("Mata Kuliah");

        jLabel5.setText("Salnan Ratih Asriningtias");

        jLabel6.setText("16048372732012");

        CBMATKUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMATKULActionPerformed(evt);
            }
        });

        jLabel7.setText("SKS                 ");

        jLabel8.setText("Nilai UTS (15%)");

        TSKS.setEditable(false);

        jLabel9.setText("Nilai UAS (15%)");

        jLabel10.setText("Nilai UKK (70%)");

        BTAMBAH.setBackground(new java.awt.Color(50, 206, 10));
        BTAMBAH.setText("Tambah");
        BTAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTAMBAHActionPerformed(evt);
            }
        });

        BRESET.setBackground(new java.awt.Color(255, 102, 102));
        BRESET.setText("Reset");
        BRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRESETActionPerformed(evt);
            }
        });

        TABELKHS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TABELKHS);

        jLabel11.setText("IPK");

        TIPK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11)
                        .addGap(97, 97, 97)
                        .addComponent(TIPK, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BRESET, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TUAS, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TUTS, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TSKS, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CBMATKUL, javax.swing.GroupLayout.Alignment.TRAILING, 0, 239, Short.MAX_VALUE)
                                .addComponent(TUKK))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBMATKUL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TUKK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTAMBAH)
                    .addComponent(BRESET))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TIPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getAccessibleContext().setAccessibleName("KHS Mahasiswa");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clear() {
        CBMATKUL.setSelectedIndex(0);
        TUTS.setText("");
        TUAS.setText("");
        TUKK.setText("");
        TIPK.setText("");
    }

    private double skala(String predikat) {
        switch (predikat) {
            case "A":
                Skala = 4;
                break;
            case "B+":
                Skala = 3.5;
                break;
            case "B":
                Skala = 3;
                break;
            case "C+":
                Skala = 2.5;
                break;
            case "C":
                Skala = 2;
                break;
            case "D+":
                Skala = 1.5;
                break;
            case "D":
                Skala = 1;
                break;
            case "E":
                Skala = 0;
                break;
            default:
                System.out.println("");
                break;
        }
        return Skala;
    }

    private String predikat(double NA) {
        if (NA > 80) {
            predikat = "A";
        } else if (75 < NA && NA <= 80) {
            predikat = "B+";
        } else if (70 < NA && NA <= 75) {
            predikat = "B";
        } else if (65 < NA && NA <= 70) {
            predikat = "C+";
        } else if (60 < NA && NA <= 65) {
            predikat = "C";
        } else if (55 < NA && NA <= 60) {
            predikat = "D+";
        } else if (50 < NA && NA <= 55) {
            predikat = "D";
        } else if (NA < 50) {
            predikat = "E";
        } else {
            System.out.println("");
        }
        return predikat;
    }

    private double hitungNA() {
        NA = (UTS * 0.15) + (UAS * 0.15) + (UKK * 0.7);
        return NA;
    }

    private void TIPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIPKActionPerformed

    private void CBMATKULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMATKULActionPerformed
        // TODO add your handling code here:

        String sks, matkul = CBMATKUL.getSelectedItem().toString();

        if (matkul.equals("Pendidikan Agama")) {
            sks = "2";
        } else if (matkul.equals("Matematika Komputasi")) {
            sks = "2";
        } else if (matkul.equals("Dasar Teknologi Informasi")) {
            sks = "3";
        } else if (matkul.equals("Jaringan Komputer")) {
            sks = "4";
        } else if (matkul.equals("Pemrograman Mobile")) {
            sks = "4";
        } else if (matkul.equals("Algoritma dan Pemrograman")) {
            sks = "3";
        } else {
            sks = "";
        }

        TSKS.setText(sks);
    }//GEN-LAST:event_CBMATKULActionPerformed

    private void BTAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAMBAHActionPerformed
        // TODO add your handling code here:
        matkul = CBMATKUL.getSelectedItem().toString();
        sks = TSKS.getText();
        uts = TUTS.getText();
        uas = TUAS.getText();
        ukk = TUKK.getText();

        try {
            if (CBMATKUL.getSelectedIndex()== 0) {
                JOptionPane.showMessageDialog(this, "Pilih Mata Kuliah terlebih dahulu",
                        "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            } else if (uts.equals("") && uas.equals("") && ukk.equals("")) {
                JOptionPane.showMessageDialog(this, "Masukkan nilai terlebih "
                        + "dahulu", "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            } else if (uts.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Masukkan nilai UTS",
                        "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            } else if (uas.equals("")) {
                JOptionPane.showMessageDialog(this, "Masukkan nilai UAS",
                        "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            } else if (ukk.equals("")) {
                JOptionPane.showMessageDialog(this, "Masukkan nilai UKK",
                        "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            }  else {
                int jumlah = TABELKHS.getRowCount();
                int i = 1;
                do {
                    UTS = Double.parseDouble(uts);
                    UAS = Double.parseDouble(uas);
                    UKK = Double.parseDouble(ukk);
                    SKS = Double.parseDouble(sks);

                    hitungNA();
                    predikat = predikat(NA);
                    Skala = skala(predikat);
                    total = Skala * SKS;
                    JTOTAL += total;
                    JSKS += SKS;
                    i++;
                } while (i <= jumlah - (jumlah - 1));

                na = Double.toString(NA);
                IPK = JTOTAL / JSKS;
                ipk = Double.toString(IPK);

                Object data[] = {matkul, sks, na, predikat};
                tabel.addRow(data);
                TABELKHS.setModel(tabel);

                CBMATKUL.setSelectedIndex(0);
                TUTS.setText("");
                TUAS.setText("");
                TUKK.setText("");
                TIPK.setText(ipk);
            }
        } catch (NumberFormatException e) {
            //validasi hanya angka 
            JOptionPane.showMessageDialog(this, "Masukan jumlah harus berupa "
                    + "angka", "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_BTAMBAHActionPerformed

    private void BRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRESETActionPerformed
        // TODO add your handling code here:
        if (TABELKHS.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Maaf, tabel kosong",
                    "KHS Mahasiswa", JOptionPane.ERROR_MESSAGE);
        } else {

            int result = JOptionPane.showConfirmDialog(this,
                    "Anda yakin ingin menghapus semua data pada tabel?",
                    "Reset",
                    JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                clear();
                tabel.getDataVector().removeAllElements();
                tabel.fireTableDataChanged();
            }
        }
    }//GEN-LAST:event_BRESETActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String ObjButtons[] = {"Ya", "Tidak"};
        int result = JOptionPane.showConfirmDialog(this, 
                        "Anda yakin ingin menutup program ini?", 
                        "KHS Mahasiswa", 
                        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
           dispose();
           Main main = new Main();
           main.setVisible(true); 
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHS_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHS_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHS_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHS_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHS_Mahasiswa().setVisible(true);
                Main main = new Main();
                main.setVisible(false); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRESET;
    private javax.swing.JButton BTAMBAH;
    private javax.swing.JComboBox<String> CBMATKUL;
    private javax.swing.JTable TABELKHS;
    private javax.swing.JTextField TIPK;
    private javax.swing.JTextField TSKS;
    private javax.swing.JTextField TUAS;
    private javax.swing.JTextField TUKK;
    private javax.swing.JTextField TUTS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
